### ISSUE TITLE
Duplicated Text For Multiple Mark Styles

### ISSUE THREAD

**Issue by fanckush** [MarvinRudolph/storyblok-rich-text-renderer#20]
Hey Again,

There is a bug in this line https://github.com/MarvinRudolph/storyblok-rich-text-renderer/blob/0dd3f50d6fb45c3ba0e2ab550d35532599fd13a5/packages/storyblok-rich-text-vue-renderer/src/renderer.ts#L47

Let's say you have the following text in Storyblok Rich Text Editor (notice it is both bold and italic):
_**I am text**_
It will be rendered as fallows:
_I am text_**I am text**

The referenced map() is likely causing the bug because it's creating as many nodes as there are marks instead of chaining them.

I might open a PR once I know how to solve it

**Comment by MarvinRudolph** [comment]
Hey, thanks for reporting! 
Yeah, it's probably because I forgot the`.reduce` and used a simple `.map`. 
Fix is on the way. 🙂
