### ISSUE TITLE
CSS class options in Rich Text

### ISSUE THREAD

**Issue by mkspeakman** [MarvinRudolph/storyblok-rich-text-renderer#3]
I'm not able to derive css class options applied to rich text elements in storyblok.

[https://www.storyblok.com/cl/css-class-options-in-rich-text](https://www.storyblok.com/cl/css-class-options-in-rich-text)

Does this package support this yet, or have I missed how? Thanks.

**Comment by MarvinRudolph** [comment]
@mkspeakman Didn't know that feature exists but yes it doesn't work atm. I'm working on a next version here https://github.com/MarvinRudolph/storyblok-rich-text-renderer/tree/next and will implement it there. The old one is now deprecated.
