### ISSUE TITLE
Vue 3 Version

### ISSUE THREAD

**Issue by aaronmyatt** [MarvinRudolph/storyblok-rich-text-renderer#7]
dear @MarvinRudolph,

I'd like to spin off a Vue 3 version of this component (unless it's in your roadmap?).

How would you like me to attribute credit to you?

Aaron.

**Comment by MarvinRudolph** [comment]
Hey @aaronmyatt, good to hear that. :) I am also working on a v3 here https://github.com/MarvinRudolph/storyblok-rich-text-renderer/tree/v3. It should be more generic, so the core renderer can be packed into a Vue.js or React plugin later. Currently, I am searching for the *best* way to do that in terms of typings and API. My time is a bit restricted at the moment, but I will try to get it done.

Feel free to fork and publish a Vue 3 version of it in the meantime. Just link to the original repository then, that should be fine. Thanks! 😊

**Comment by aaronmyatt** [comment]
@MarvinRudolph I'll explore your work first and see if I can assist

**Comment by aaronmyatt** [comment]
> @MarvinRudolph I'll explore your work first and see if I can assist

Ah! I see your repo is till in a very nascent state 😄 I'll fork after all

**Comment by AlexanderFalkenberg** [comment]
any news on this? :)
